name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install
      # Skip post-install to avoid malicious scripts stealing PAT
      run: npm ci --ignore-scripts --min-release-age=0
      env:
        # GITHUB_TOKEN can't access packages hosted in private repos,
        # even within the same organisation
        NODE_AUTH_TOKEN: ${{ secrets.REEDSY_BOT_PERSONAL_ACCESS_TOKEN }}
    - name: Post-install
      run: npm rebuild && npm run prepare --if-present
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
    - name: Release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: ./release.sh
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
